import java.time.LocalDate
import java.time.format.DateTimeFormatter

import static org.gradle.api.file.DuplicatesStrategy.INCLUDE
import static org.jreleaser.model.Active.ALWAYS

plugins {
    id 'groovy-gradle-plugin'
    id 'maven-publish'
    id 'org.jreleaser' version "$jreleaserVersion"
}

group = 'io.github.pluxurydolo'
version = file('version.properties').withInputStream {
    Properties props = new Properties()
    props.load(it)
    props.getProperty('VERSION')
}

java {
    withJavadocJar()
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

gradlePlugin {
    plugins {
        infrastructurePlugin {
            id = 'io.github.pluxurydolo.infrastructure-plugin'
            implementationClass = 'com.pluxurydolo.InfrastructurePlugin'
        }
    }
}

processResources {
    duplicatesStrategy = INCLUDE
    from 'src/main/resources'
    into 'templates'
}

afterEvaluate {
    publishing {
        publications {
            withType(MavenPublication).configureEach {
                pom {
                    name = 'infrastructure-plugin'
                    description = 'Infrastructure Plugin made for personal use'
                    url = 'https://github.com/pluxurydolo/infrastructure-plugin'

                    developers {
                        developer {
                            id = 'pluxurydolo'
                            name = 'Alexander'
                        }
                    }

                    scm {
                        url = 'scm:git:git://github.com/infrastructure-plugin.git'
                        connection = 'scm:git:git://github.com/infrastructure-plugin.git'
                        tag = project.version
                    }

                    licenses {
                        license {
                            name = 'The Apache License, Version 2.0'
                            url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                        }
                    }
                }
            }
        }

        repositories {
            maven {
                url = uri layout.buildDirectory.dir('staging-deploy')
            }
        }
    }
}

jreleaser {
    release {
        github {
            skipRelease.set true
            skipTag.set true
        }
    }

    signing {
        active.set ALWAYS
        armored.set true
        verify.set true
    }

    project {
        inceptionYear.set '2026'
        author('@pluxurydolo')
    }

    deploy {
        maven {
            mavenCentral.create('sonatype') {
                active.set ALWAYS
                url = 'https://central.sonatype.com/api/v1/publisher'
                stagingRepository layout.buildDirectory.dir('staging-deploy').get().toString()
                setAuthorization 'Basic'
                retryDelay.set 60
            }
        }
    }
}

tasks.register('bumpVersion') {
    group = 'version'

    doLast {
        Properties props = new Properties()

        File versionFile = file('version.properties')
        versionFile.withInputStream { props.load(it) }

        String lastCommitDate = getLastCommitDate()
        String lastModifiedDate = props.getProperty('LAST_MODIFIED_DATE', lastCommitDate)

        int majorVersion = props.getProperty('VERSION_MAJOR').toInteger()
        int minorVersion = props.getProperty('VERSION_MINOR').toInteger()
        int patchVersion = props.getProperty('VERSION_PATCH').toInteger()

        if (isDateAfter(lastCommitDate, lastModifiedDate)) {
            minorVersion++
            patchVersion = 0
        } else if (patchVersion == 0 && lastModifiedDate == lastCommitDate) {
            project.logger.lifecycle("zylw [infrastructure-plugin] Версия $majorVersion.$minorVersion.$patchVersion свежая, патч-номер не увеличится")
            return
        } else {
            patchVersion++
        }

        String version = "$majorVersion.$minorVersion.$patchVersion"
        project.logger.lifecycle("wgiq [infrastructure-plugin] Новая версия проекта: $version")

        props.setProperty('VERSION_MAJOR', majorVersion.toString())
        props.setProperty('VERSION_MINOR', minorVersion.toString())
        props.setProperty('VERSION_PATCH', patchVersion.toString())

        props.setProperty('VERSION', version)
        props.setProperty('LAST_MODIFIED_DATE', lastCommitDate)

        versionFile.withOutputStream { props.store(it, null) }
    }
}

static String getLastCommitDate() {
    return 'git log -1 --format=%cd --date=short'.execute().text.trim()
}

static boolean isDateAfter(String date1, String date2) {
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern('yyyy-MM-dd')
    LocalDate localDate1 = LocalDate.parse(date1, formatter)
    LocalDate localDate2 = LocalDate.parse(date2, formatter)
    return localDate1.isAfter(localDate2)
}
