import java.time.LocalDate

import static org.gradle.api.file.DuplicatesStrategy.INCLUDE
import static org.jreleaser.model.Active.ALWAYS

plugins {
    id 'groovy-gradle-plugin'
    id 'maven-publish'
    id 'org.jreleaser' version "$jreleaserVersion"
}

group = 'io.github.pluxurydolo'
version = bumpAndGetVersion(false)

java {
    withJavadocJar()
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

gradlePlugin {
    plugins {
        infrastructurePlugin {
            id = 'io.github.pluxurydolo.infrastructure-plugin'
            implementationClass = 'com.pluxurydolo.InfrastructurePlugin'
        }
    }
}

processResources {
    duplicatesStrategy = INCLUDE
    from 'src/main/resources'
    into 'templates'
}

afterEvaluate {
    publishing {
        publications {
            withType(MavenPublication).configureEach {
                pom {
                    name = 'infrastructure-plugin'
                    description = 'Infrastructure Plugin made for personal use'
                    url = 'https://github.com/pluxurydolo/infrastructure-plugin'

                    developers {
                        developer {
                            id = 'pluxurydolo'
                            name = 'Alexander'
                        }
                    }

                    scm {
                        url = 'scm:git:git://github.com/infrastructure-plugin.git'
                        connection = 'scm:git:git://github.com/infrastructure-plugin.git'
                        tag = project.version
                    }

                    licenses {
                        license {
                            name = 'The Apache License, Version 2.0'
                            url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                        }
                    }
                }
            }
        }

        repositories {
            maven {
                url = uri layout.buildDirectory.dir('staging-deploy')
            }
        }
    }
}

jreleaser {
    release {
        github {
            skipRelease.set true
            skipTag.set true
        }
    }

    signing {
        active.set ALWAYS
        armored.set true
        verify.set true
    }

    project {
        inceptionYear.set '2026'
        author('@pluxurydolo')
    }

    deploy {
        maven {
            mavenCentral.create('sonatype') {
                active.set ALWAYS
                url = 'https://central.sonatype.com/api/v1/publisher'
                stagingRepository layout.buildDirectory.dir('staging-deploy').get().toString()
                setAuthorization 'Basic'
                retryDelay.set 60
            }
        }
    }
}

tasks.register('bumpVersion') {
    group = 'version'

    doLast {
        bumpAndGetVersion(true)
    }
}

String bumpAndGetVersion(boolean force) {
    Properties props = new Properties()
    File versionFile = file('version.properties')
    versionFile.withInputStream { props.load(it) }

    if (!isCI() && !force) {
        return props.getProperty('VERSION')
    }

    String currentDate = LocalDate.now().toString()
    String lastModifiedDate = props.getProperty('LAST_MODIFIED_DATE', currentDate)

    int major = props.getProperty('VERSION_MAJOR').toInteger()
    int minor = props.getProperty('VERSION_MINOR').toInteger()
    int patch = props.getProperty('VERSION_PATCH').toInteger()

    if (patch == -1) {
        patch = 0
    } else if (currentDate > lastModifiedDate) {
        minor++
        patch = 0
    } else {
        patch++
    }

    String version = "$major.$minor.$patch"
    println "ukqf [infrastructure-plugin] Новая версия проекта: $version"

    props.setProperty('VERSION_MAJOR', major.toString())
    props.setProperty('VERSION_MINOR', minor.toString())
    props.setProperty('VERSION_PATCH', patch.toString())
    props.setProperty('VERSION', version)
    props.setProperty('LAST_MODIFIED_DATE', currentDate)

    versionFile.withOutputStream { props.store(it, null) }

    return version
}

static boolean isCI() {
    return System.getenv('CI') == 'true' || System.getenv('GITHUB_ACTIONS') == 'true'
}
